id: opecha:P000372
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22265
  title: དབུ་མ་འཇུག་པའི་སྤྱི་དོན་ལེགས་བཤད་སྐལ་བཟང་མགུལ་རྒྱན།
  volume:
    c2ea5ec32dfa49bc9dfe9da5f83da085:
      image_group_id: I1KG22283
      title: Volume 1 of dbu ma 'jug pa'i spyi don legs bshad skal bzang mgul rgyan/
      volume_number: 1
      total_pages: 326
  author: ''
ebook_metadata:
  title: དབུ་མ་འཇུག་པའི་སྤྱི་དོན་ལེགས་བཤད་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  sku: P000372
  cover: cover.jpg
  layers:
  - pagination
